key: tasks
state: READY
errors: []
isDeactivated: false
id: 681a4e3c0d6a7236439b5d31
name: Tasks
customized: false
universalFieldMappingId: 681a4e33656f7d57d6530b20
integrationId: 681a4e2c5f4cb1dd06e1c6f2
dataSourceKey: tasks
appSchema:
  type: object
  properties:
    id:
      type: string
    title:
      type: string
    description:
      type: string
    assigneeId:
      type: string
    projectId:
      type: string
    status:
      type: string
direction: both
defaultImportValue:
  id:
    $var: $.id
  title:
    $var: $.subject
  description:
    $var: $.content
  status:
    $var: $.status
  projectId:
    $var: $.projectId
  assigneeId:
    $var: $.assigneeId
defaultExportValue:
  subject:
    $var: $.title
  content:
    $var: $.description
  status:
    $var: $.status
  ownerId:
    $var: $.assigneeId
exportValue:
  summary:
    $var: $.title
  assignee:
    $var: $.assigneeId
  description:
    $var: $.description
  status:
    id:
      $var: $.status
  reporter:
    $var: $.assigneeId
importValue:
  id:
    $var: $.id
  title:
    $var: $.summary
  description:
    $var: $.description
  status:
    $var: $.status.id
  projectId:
    $var: $.project
  assigneeId:
    $var: $.assignee
integration:
  key: jira
  state: READY
  errors: []
  isDeactivated: false
  id: 681a4e2c5f4cb1dd06e1c6f2
  name: Jira
  uuid: dcfbf52a-0e90-4bd4-8d39-aa6f21aa3081
  connectorId: 64343d08986ed1caad5b3aa7
  hasDefaultParameters: false
  hasMissingParameters: false
  hasDocumentation: true
  hasOperations: true
  hasData: true
  hasEvents: false
  hasGlobalWebhooks: false
  hasUdm: true
  areParametersCustomized: false
  baseUri: s3://integration-app-connectors/public/9c8c0930-c1fb-4678-ba3e-0f43adce9e9e
  connectorVersion: 1.4.12
  logoUri: https://static.integration.app/connectors/jira/logo.png
  dataCollectionsCount: 12
  operationsCount: 499
  eventsCount: 0
  authType: oauth2
integrationKey: jira
